allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.addAll(['-Xlint:none', '-nowarn'])
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
